version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "region us-east-1"
    HUGO_VERSION: "0.63.0"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - chmod +x hugo
      - mv hugo /usr/local/bin/
      - cd - 
      - rm -rf /tmp/*
      - hugo version
  build:
    commands:
      - rm -rf public
      - hugo
   #  - aws s3 sync public/ s3://hugo-deployment/ --delete --acl public-read
      - aws s3 sync --delete public s3://hugo-deployment --cache-control "max-age=3600, public" --exclude "*" --include "*.html" --include "*.xml"
      - aws s3 sync --delete public s3://hugo-deployment --cache-control "max-age=86400, public" --exclude "*.html" --exclude "*.xml"

  post_build:
    commands:
      - echo Build completed on `date`