version: 0.2

environment_variables:
  plaintext:
    s3_output: "hugo-deployment"
    HUGO_VERSION: "0.62.0"
    
phases:
  install:
    runtime-versions:
      docker: 19
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - ls -la /usr/bin/hugo
      - cd -
      - rm -rf /tmp/*
  build:
    commands:
      - rm -rf public
      - hugo
  post_build:
    commands:
      - aws s3 ls s3://hugo-deployment/
      - aws s3 sync public/ s3://${s3_output}/ --region us-east-1 --delete
      - aws s3 ls s3://hugo-deployment/
      - echo Build completed on `date`