version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "region us-east-1"
    HUGO_VERSION: "0.63.0"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv /tmp/hugo ~/bin/hugo
      - rm -rf /tmp/hugo*

  build:
    commands:
  #   - rm -rf public
      - hugo
      - aws s3 sync ./public s3://hugo-deployment --delete # upload the site to S3

  post_build:
    commands:
      - echo Build completed on `date`