version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "region us-east-1"
    HUGO_VERSION: "0.63.0"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - wget https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /tmp
     -  mv /tmp/hugo_${HUGO_VERSION}_linux_amd64/hugo_${HUGO_VERSION}_linux_amd64 ~/bin/hugo
      - rm -rf /tmp/hugo*

  build:
    commands:
  #   - rm -rf public
      - hugo
      - aws s3 sync ./public s3://hugo-deployment --delete # upload the site to S3

  post_build:
    commands:
      - echo Build completed on `date`