version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.63.0"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - chmod +x hugo
      - mv hugo /usr/local/bin/
      - cd - 
      - rm -rf /tmp/*
  build:
    commands:
     #- rm -rf public
      - hugo
      - echo "S3 Upload Beginning"
      - cd public && aws s3 sync . s3://hugo-deployment/ --region us-east-1 --delete --acl public-read
      - echo "S3 Upload Complete"
  post_build:
    commands:
      - echo Build completed on `date`