version: 0.2

environment_variables:
  plaintext:
    s3_output: "hugo-deployment"
    HUGO_VERSION: "0.62.0"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb"
      - dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
    finally:
      - hugo version
  build:
    commands:
      - hugo
      - cd public && aws s3 sync . s3://${s3_output} --region us-east-1 --delete --acl public-read
    finally:
      - echo "Script finished running"