version: 0.2

environment_variables:
  plaintext:
    s3_output: "hugo-deployment"
    HUGO_VERSION: "0.62.0"
    
phases:
  install:
    runtime-versions:
      docker: 18
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo_${HUGO_VERSION}_Linux-64bit.tar.gz /home/ubuntu
      - cd /home/ubuntu/
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - pwd
      - ls -la
     # - cp -r hugo /home/ubuntu/bin/hugo/
      - cd - 
      #- rm -rf /tmp/*
    finally:
      - hugo version
      - which hugo
  build:
    commands:
      - hugo
      - cd public && aws s3 sync . s3://${s3_output} --region us-east-1 --delete --acl public-read
    finally:
      - echo "Script finished running"
artifacts:
    files:
      - '**/*'
    base-directory: 'public'