baseURL = "http://hugo-deployment.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "My New Hugo Site with Continuos Deployment via AWS Cloud9"
theme = "ananke"

[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://hugo-deployment/?region=us-east-1" #your public bucket here
